# Default values for hello-from-container.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: antonhlinisty/hello-from-container
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

